services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    ports:
      - 9200:9200
    container_name: be-vn-cultural-gis-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ingest.geoip.downloader.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.0
    container_name: be-vn-cultural-gis-kibana
    depends_on:
      - elasticsearch
    environment:
      - SERVER_HOST=0.0.0.0
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    ports:
      - 5601:5601

  logstash:
    build:
      context: ./logstash
    container_name: be-vn-cultural-gis-logstash
    depends_on:
      - elasticsearch
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.monitoring.enabled=false
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL:-http://elasticsearch:9200}
      - ELASTICSEARCH_PLACES_INDEX=${ELASTICSEARCH_PLACES_INDEX:-places}
      - ELASTICSEARCH_PLACE_LOCATIONS_INDEX=${ELASTICSEARCH_PLACE_LOCATIONS_INDEX:-place_locations}
      - JDBC_CONNECTION_STRING=${JDBC_CONNECTION_STRING:-jdbc:mysql://host.docker.internal:3306/vn_cultural_gis?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
      - JDBC_USER=${JDBC_USER:-root}
      - JDBC_PASSWORD=${JDBC_PASSWORD:-1234}
    volumes:
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/jdbc_last_run:/usr/share/logstash/jdbc_last_run
    ports:
      - 8081:8081
      - 9600:9600

volumes:
  elasticsearch-data:
