const UserRoute = require('./UserRoute');
const AuthRoute = require('./AuthRoute');
const PostRoute = require('./PostRouter');
const PlaceRoute = require('./PlaceRouter');
const LocationRoute = require('./LocationRouter');
const CategoryRoute = require('./CategoryRouter');
const SearchRoute = require('./SearchRouter');
const CommentRoute = require('./CommentRouter');
const NotificationRoute = require('./NotificationRouter');
const CuisineRoute = require('./CuisineRouter');
const CustomRoute = require('./CustomRouter');
const FolkArtRoute = require('./FolkArtRouter');
const ExhibitionRoute = require('./ExhibitionRouter');
const AuthManager = require('../manager/authManager');
const SettingRoute = require('./SettingRouter');
const ReviewRoute = require('./ReviewRouter');
const PackageRoute = require('./PackageRouter');
const SubscriptionRoute = require('./SubscriptionRouter');
const ProductRoute = require('./ProductRouter');
const HolidayRoute = require('./HolidayRouter');

const initRoutes = (app) =>{
    app.post("/api/v1/login", AuthManager.login);
    app.use("/api/v1/auth", AuthRoute);
    app.use("/api/v1/user", UserRoute);
    app.use("/api/v1/post", PostRoute);
    app.use("/api/v1/place", PlaceRoute);
    app.use("/api/v1/location", LocationRoute);
    app.use("/api/v1/category", CategoryRoute);
    app.use("/api/v1/search", SearchRoute);
    app.use("/api/v1/comment",CommentRoute);
    app.use("/api/v1/notification", NotificationRoute);
    app.use("/api/v1/cuisine", CuisineRoute);
    app.use("/api/v1/custom", CustomRoute);
    app.use("/api/v1/folk-art", FolkArtRoute);
    app.use("/api/v1/exhibition", ExhibitionRoute);
    app.use("/api/v1/setting", SettingRoute);
    app.use("/api/v1/review", ReviewRoute);
    app.use("/api/v1/package", PackageRoute);
    app.use("/api/v1/subscription", SubscriptionRoute);
    app.use("/api/v1/product", ProductRoute);
    app.use("/api/v1/holiday", HolidayRoute);
}
module.exports = initRoutes;