input {
  http {
    port => 8081
    codec => json
  }
}

filter {
  mutate {
    add_field => {
      "service" => "be-vn-cultural-gis"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
