input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/vendor/jar/jdbc/mysql-connector-j.jar"
    jdbc_driver_class => "com.mysql.cj.jdbc.Driver"

    jdbc_connection_string => "${JDBC_CONNECTION_STRING}"
    jdbc_user => "${JDBC_USER}"
    jdbc_password => "${JDBC_PASSWORD}"
    clean_run => true
    schedule => "*/5 * * * *"

    statement => "
        SELECT 
        id,
        name, 
        description, 
        category_id, 
        created_at, 
        updated_at 
        FROM places 
        WHERE updated_at > :sql_last_value 
        ORDER BY updated_at ASC
    "

    use_column_value => true
    tracking_column => "updated_at"
    tracking_column_type => "timestamp"

    record_last_run => true
    last_run_metadata_path => "/usr/share/logstash/jdbc_last_run/places.yml"

    jdbc_paging_enabled => true
    jdbc_page_size => 1000
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "${ELASTICSEARCH_PLACES_INDEX}"
    document_id => "%{id}"
  }
  stdout {
    codec => rubydebug
  }
}
